# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

ContGrid <- function(xc, xg, y, x2, y2, lamb1, lamb2, bc0, bg0, r, a, p, pc, robust, method, debugging, maxit, tol) {
    .Call(`_regnet_ContGrid`, xc, xg, y, x2, y2, lamb1, lamb2, bc0, bg0, r, a, p, pc, robust, method, debugging, maxit, tol)
}

LogitGrid <- function(x, y, x2, y2, lamb1, lamb2, b, r, a, p, alpha, method, maxit, tol) {
    .Call(`_regnet_LogitGrid`, x, y, x2, y2, lamb1, lamb2, b, r, a, p, alpha, method, maxit, tol)
}

RunCont <- function(xc, xg, y, lamb1, lamb2, bc, bg, r, a, triRowAbsSums, p, pc, method, maxit, tol) {
    .Call(`_regnet_RunCont`, xc, xg, y, lamb1, lamb2, bc, bg, r, a, triRowAbsSums, p, pc, method, maxit, tol)
}

RunCont_robust <- function(xc, xg, y, lamb1, lamb2, bc, bg, r, a, p, pc, method, debugging, maxit, tol) {
    .Call(`_regnet_RunCont_robust`, xc, xg, y, lamb1, lamb2, bc, bg, r, a, p, pc, method, debugging, maxit, tol)
}

RunLogit <- function(x, y, lamb1, lamb2, b, r, a, triRowAbsSums, p, alpha, method, maxit, tol) {
    .Call(`_regnet_RunLogit`, x, y, lamb1, lamb2, b, r, a, triRowAbsSums, p, alpha, method, maxit, tol)
}

RunNet <- function(x, y, lamb1, lamb2, b, r, a, p, maxit, tol) {
    .Call(`_regnet_RunNet`, x, y, lamb1, lamb2, b, r, a, p, maxit, tol)
}

RunMCP <- function(x, y, lambda, b, r, p, maxit, tol) {
    .Call(`_regnet_RunMCP`, x, y, lambda, b, r, p, maxit, tol)
}

RunElastic <- function(x, y, lambda, b, alpha, p, maxit, tol) {
    .Call(`_regnet_RunElastic`, x, y, lambda, b, alpha, p, maxit, tol)
}

RunSurv_robust <- function(xc, xg, y, lamb1, lamb2, bc, bg, r, a, p, pc, method, debugging, maxit, tol) {
    .Call(`_regnet_RunSurv_robust`, xc, xg, y, lamb1, lamb2, bc, bg, r, a, p, pc, method, debugging, maxit, tol)
}

RunSurv <- function(xc, xg, y, lamb1, lamb2, bc, bg, r, a, triRowAbsSums, p, pc, method, maxit, tol) {
    .Call(`_regnet_RunSurv`, xc, xg, y, lamb1, lamb2, bc, bg, r, a, triRowAbsSums, p, pc, method, maxit, tol)
}

SurvGrid <- function(xc, xg, y, x2, y2, lamb1, lamb2, bc, bg, r, a, p, pc, robust, method, debugging, maxit, tol) {
    .Call(`_regnet_SurvGrid`, xc, xg, y, x2, y2, lamb1, lamb2, bc, bg, r, a, p, pc, robust, method, debugging, maxit, tol)
}

